<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2002-2006 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />

<title>Action Message Boards &bull; Index page</title>

<!--
	phpBB style name: New Life
	Based on style:   New Life
	Original author:  Robin Huurman ( http://www.phpbb-stylers.com/ )
	Modified by:      
	
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	

	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (i = 0; i <= onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (i = 0; i <= onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/new-life/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/new-life/template/forum_fn.js"></script>

<!--[if lt IE 7.]>
<script defer type="text/javascript" src="./styles/new-life/template/pngfix.js"></script>
<![endif]-->

<link href="./styles/new-life/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?id=6&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/new-life/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/new-life/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/new-life/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />



</head>

<body id="phpbb" class="section-index ltr">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner">
            
            <div class="mainnav">
            	<ul>
                	<li><a href="./index.php"><span>Board index</span></a></li>
                    <li><a href="./faq.php"><span>FAQ</span></a></li>
                    
                    <li class="searchfield">
                    	<form action="./search.php" method="post" id="search">
                        <fieldset>
                            <input name="keywords" id="keywords" type="text" maxlength="128" title="Search for keywords" class="inputbox mainsearch" value="Search…" onclick="if(this.value=='Search…')this.value='';" onblur="if(this.value=='')this.value='Search…';" />
                        </fieldset>
                        </form>
                    </li>
                </ul>
            </div>

			<div id="site-description">
				<a href="./index.php" title="Board index" id="logo"><img src="./styles/new-life/imageset/site_logo.png" width="178" height="100" alt="" title="" /></a>
			</div>

			</div>
		</div>
        
        <div style="clear: both"></div>

		
        
        <div class="padder">
        	<p class="rightside">
        	
			 &bull; <a href="./search.php?search_id=egosearch">View your posts</a>
        	
            </p>
            <p><a href="./index.php" accesskey="h">Board index</a> </p>
        </div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">
		
        <div class="padder">
		 
        </div>

<div class="padder">
<p class="right rightside">Last visit was: Mon May 27, 2013 4:25 pm</p>
<p>It is currently Mon May 27, 2013 4:25 pm</p>
</div>


 		<div class="foratop"></div>
		<div class="forabg">
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=21">News</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=10" class="forumtitle">News</a><br />
					News about the site
					
						<br /><strong>Moderator:</strong> <span>Super Moderators</span>
					
				</dt>
				
					<dd class="topics">34 <dfn>Topics</dfn></dd>
					<dd class="posts">622 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Cowman
						<a href="./viewtopic.php?f=10&amp;p=34249#p34249"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Wed Feb 20, 2013 10:51 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>
            
		</div>
        <div class="forabottom"></div>
	
 		<div class="foratop"></div>
		<div class="forabg">
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=31">Action Half Life 2</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=32" class="forumtitle">AHL 2 - General</a><br />
					General Action Half Life 2 Discussion
					
						<br /><strong>Moderator:</strong> <span>General Moderators</span>
					
				</dt>
				
					<dd class="topics">3 <dfn>Topics</dfn></dd>
					<dd class="posts">49 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Kissamies
						<a href="./viewtopic.php?f=32&amp;p=33291#p33291"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Tue Sep 08, 2009 7:52 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=33" class="forumtitle">AHL 2 - Help / FAQ</a><br />
					Get help with Action Half Life 2 here, as well as answers to frequently asked questions.
					
						<br /><strong>Moderator:</strong> <span>General Moderators</span>
					
				</dt>
				
					<dd class="topics">1 <dfn>Topics</dfn></dd>
					<dd class="posts">5 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by <span style="color: #AA0000;" class="username-coloured">Framer</span>
						<a href="./viewtopic.php?f=33&amp;p=32948#p32948"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Wed Jul 01, 2009 4:37 am</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_subforum.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=34" class="forumtitle">AHL 2 - Content Creation</a><br />
					
					
				</dt>
				
					<dd class="topics">2 <dfn>Topics</dfn></dd>
					<dd class="posts">9 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by <span style="color: #AA0000;" class="username-coloured">Framer</span>
						<a href="./viewtopic.php?f=35&amp;p=32949#p32949"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Wed Jul 01, 2009 4:44 am</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>
            
		</div>
        <div class="forabottom"></div>
	
 		<div class="foratop"></div>
		<div class="forabg">
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=23">Action Mods</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=3" class="forumtitle">Action UT</a><br />
					Action Unreal Tournament Discussion
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>, <span>Mod Moderators</span>
					
				</dt>
				
					<dd class="topics">22 <dfn>Topics</dfn></dd>
					<dd class="posts">409 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Hawky
						<a href="./viewtopic.php?f=3&amp;p=33445#p33445"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Sat Nov 14, 2009 4:48 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=4" class="forumtitle">Action Half Life</a><br />
					Action Half Life Discussion
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>, <span>Mod Moderators</span>
					
				</dt>
				
					<dd class="topics">114 <dfn>Topics</dfn></dd>
					<dd class="posts">1410 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by White_Rabbit
						<a href="./viewtopic.php?f=4&amp;p=33512#p33512"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Fri Dec 18, 2009 7:22 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=5" class="forumtitle">Action Quake 2</a><br />
					Action Quake 2 Discussion
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>, <span>Mod Moderators</span>
					
				</dt>
				
					<dd class="topics">105 <dfn>Topics</dfn></dd>
					<dd class="posts">1190 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Lurker
						<a href="./viewtopic.php?f=5&amp;p=33500#p33500"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Thu Dec 03, 2009 3:12 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>
            
		</div>
        <div class="forabottom"></div>
	
 		<div class="foratop"></div>
		<div class="forabg">
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=24">General</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=2" class="forumtitle">Silly Hats Only</a><br />
					No regular hats in here!
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>
					
				</dt>
				
					<dd class="topics">1268 <dfn>Topics</dfn></dd>
					<dd class="posts">23895 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by No Fear
						<a href="./viewtopic.php?f=2&amp;p=34243#p34243"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Wed Aug 29, 2012 8:55 am</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=6" class="forumtitle">Movie Reviews</a><br />
					Post your Movie reviews here!
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>
					
				</dt>
				
					<dd class="topics">193 <dfn>Topics</dfn></dd>
					<dd class="posts">1807 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by bantam
						<a href="./viewtopic.php?f=6&amp;p=33709#p33709"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Mon Jul 05, 2010 4:43 am</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=7" class="forumtitle">Product Reviews</a><br />
					Post your Product reviews here!
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>
					
				</dt>
				
					<dd class="topics">41 <dfn>Topics</dfn></dd>
					<dd class="posts">411 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Ilkimys
						<a href="./viewtopic.php?f=7&amp;p=32696#p32696"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Sun May 31, 2009 6:46 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=11" class="forumtitle">Game Reviews</a><br />
					You know, reviews for PC, XBOX, PS, PS2, PSP, etc..
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>
					
				</dt>
				
					<dd class="topics">125 <dfn>Topics</dfn></dd>
					<dd class="posts">1278 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by <span style="color: #AA0000;" class="username-coloured">Ace12GA</span>
						<a href="./viewtopic.php?f=11&amp;p=34186#p34186"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Mon Jul 11, 2011 3:19 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>
            
		</div>
        <div class="forabottom"></div>
	
 		<div class="foratop"></div>
		<div class="forabg">
			<ul class="topiclist">
				<li class="header">
					<dl class="icon">
						<dt><a href="./viewforum.php?f=25">Content Creation</a></dt>
						<dd class="topics">Topics</dd>
						<dd class="posts">Posts</dd>
						<dd class="lastpost"><span>Last post</span></dd>
					</dl>
				</li>
			</ul>
			<ul class="topiclist forums">
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=13" class="forumtitle">Haven O' Frags</a><br />
					AHL Replacement Models
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>, <span>Content Moderators</span>
					
				</dt>
				
					<dd class="topics">16 <dfn>Topics</dfn></dd>
					<dd class="posts">249 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by PsyCHo
						<a href="./viewtopic.php?f=13&amp;p=31815#p31815"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Sat Mar 07, 2009 12:44 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=15" class="forumtitle">AHLMD</a><br />
					Action Half Life Map Depot
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>, <span>Content Moderators</span>
					
				</dt>
				
					<dd class="topics">24 <dfn>Topics</dfn></dd>
					<dd class="posts">223 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by Hawky
						<a href="./viewtopic.php?f=15&amp;p=32400#p32400"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Thu Apr 30, 2009 7:14 pm</span>
					</dd>
				
			</dl>
		</li>
	
		<li class="row">
			<dl class="icon" style="background-image: url(./styles/new-life/imageset/forum_read_locked.gif); background-repeat: no-repeat;">
				<dt>
					
					<a href="./viewforum.php?f=14" class="forumtitle">AQMD</a><br />
					Action Quake Map Depot
					
						<br /><strong>Moderators:</strong> <span>General Moderators</span>, <span>Super Moderators</span>, <span>Content Moderators</span>
					
				</dt>
				
					<dd class="topics">4 <dfn>Topics</dfn></dd>
					<dd class="posts">44 <dfn>Posts</dfn></dd>
					<dd class="lastpost"><span>
						<dfn>Last post</dfn> by <span style="color: #AA0000;" class="username-coloured">Ace12GA</span>
						<a href="./viewtopic.php?f=14&amp;p=25793#p25793"><img src="./styles/new-life/imageset/icon_topic_latest.gif" width="11" height="9" alt="View the latest post" title="View the latest post" /></a> <br />on Tue Sep 04, 2007 12:10 pm</span>
					</dd>
				
			</dl>
		</li>
	
			</ul>

		</div>
        <div class="forabottom"></div>
	

<div class="padder">
<h3>Who is online</h3>
	<p>In total there is <strong>1</strong> user online :: 1 registered, 0 hidden and 0 guests (based on users active over the past 5 minutes)<br />Most users ever online was <strong>130</strong> on Fri Jun 29, 2007 8:10 pm<br /> <br />Registered users: <span style="color: #9E8DA7;" class="username-coloured">Alexa [Bot]</span>
	<br /><em>Legend: <span style="color:#AA0000">Administrators</span>, <span style="color:#00AA00">Global moderators</span></em></p>

	<h3>Birthdays</h3>
	<p>Congratulations to: <strong>Bloodwolf, sophiag6 (37), WowGoldGuidesOr (33)</strong></p>

	<h3>Statistics</h3>
	<p>Total posts <strong>33534</strong> &bull; Total topics <strong>2406</strong> &bull; Total members <strong>493</strong> &bull; Our newest member <strong>gooseremasony</strong></p>

</div>

</div>

<div id="page-footer">
	
    <div class="foratop"></div>
	<div class="forabg">

		<ul class="linklist forums">
			<li><a href="./index.php" accesskey="h">Board index</a></li>
				
			<li class="rightside"><a href="">The team</a> &bull; All times are UTC </li>
		</ul>

	</div>
    <div class="forabottom"></div>
	
<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright">Powered by <a href="http://www.phpbb.com/">phpBB</a> &copy; 2007 phpBB Group | Theme &copy; 2008 by <a href="http://www.phpbb-stylers.com">Robin Huurman</a>
		
	</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	
</div>

</body>
</html>